name: Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Terraform Fmt
        run: terraform -chdir=envs/${{ matrix.env }} fmt -check

      - name: Terraform Init
        run: terraform -chdir=envs/${{ matrix.env }} init -upgrade

      - name: Terraform Validate
        run: terraform -chdir=envs/${{ matrix.env }} validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=envs/${{ matrix.env }} plan -input=false

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=envs/${{ matrix.env }} apply -auto-approve -input=false
